// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIsiSY9Pa2Hwtshjs-_VQKEEfcryV2DY0',
    appId: '1:832227520024:web:8db25ce1aec18d24b9dd6d',
    messagingSenderId: '832227520024',
    projectId: 'crypticcam-5f318',
    authDomain: 'crypticcam-5f318.firebaseapp.com',
    storageBucket: 'crypticcam-5f318.firebasestorage.app',
    measurementId: 'G-ZHFJK83FQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiQPDhMY5kSQOENm2w_Y312yMckZOdj94',
    appId: '1:832227520024:android:a28117c8bbee909bb9dd6d',
    messagingSenderId: '832227520024',
    projectId: 'crypticcam-5f318',
    storageBucket: 'crypticcam-5f318.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEWyXHySHLQ4IvZdXAMIWF1u1zCNjNc0A',
    appId: '1:832227520024:ios:02fb458c72e939f3b9dd6d',
    messagingSenderId: '832227520024',
    projectId: 'crypticcam-5f318',
    storageBucket: 'crypticcam-5f318.firebasestorage.app',
    iosBundleId: 'com.example.cripticam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEWyXHySHLQ4IvZdXAMIWF1u1zCNjNc0A',
    appId: '1:832227520024:ios:02fb458c72e939f3b9dd6d',
    messagingSenderId: '832227520024',
    projectId: 'crypticcam-5f318',
    storageBucket: 'crypticcam-5f318.firebasestorage.app',
    iosBundleId: 'com.example.cripticam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIsiSY9Pa2Hwtshjs-_VQKEEfcryV2DY0',
    appId: '1:832227520024:web:711aa8dcc74b0f12b9dd6d',
    messagingSenderId: '832227520024',
    projectId: 'crypticcam-5f318',
    authDomain: 'crypticcam-5f318.firebaseapp.com',
    storageBucket: 'crypticcam-5f318.firebasestorage.app',
    measurementId: 'G-188E93MXV1',
  );
}
